### ISSUE TITLE
[InvalidArgumentException]

### ISSUE THREAD

**Issue by motioncompany** [matomo-org/plugin-Migration#17]
Hello,
when I start the command
./console migration:measurable --dry-run --source-idsite=1 --target-db-host=x.x.x.x --target-db-username=root --target-db-password=xxxxxx --target-db-name=stats-TEST

I get the error:
Uncaught exception: /home/xxxxx/htdocs/stats/vendor/symfony/console/Symfony/Component/Console/Application.php(501): There are no commands defined in the "migration" namespace.
There are no commands defined in the "migration" namespace.

I use Matomo 3.13.3 on both sides.

Any ideas?

**Comment by tsteur** [comment]
Hi there, it likely means you need to enable this plugin first eg using `./console plugin:activate Migration`. Or you can also do it through the UI by going to Administration => Plugins.

Cheers,
Thomas
