### ISSUE TITLE
Command "migration" is not defined.

### ISSUE THREAD

**Issue by bitsvital** [matomo-org/plugin-Migration#18]
Hi, trying to move one site over to another Matomo server.
I run the command
`./console migration --source-idsite=1 --target-db-host=newserver --target-db-username=mySQLusername --target-db-password=secure --target-db-name=databaseName`
I receive this error
`[InvalidArgumentException]           
  Command "migration" is not defined.`

**Comment by tsteur** [comment]
@bitsvital the command is `migration:measurable`. Also make sure the plugin is activated.

**Comment by bitsvital** [comment]
My apologizes...type on migration:measurable
The problem was that I did not activate the plugin. First time using ./console. I was not aware I needed to activate the plugin. 
Thank you!

**Comment by skaragoez** [comment]
Hello, 
I have same issue even though i activated the plugin with `plugin:activate`. Plugin is listed in the plugin list but the status is **Not activated** and also the commands are not available.

```
| WordPress         | Optional          | Activated     |
| Migration          | Optional          | Not activated |
```

I'v matomo wordpress (6.0.2) plugin (4.11.0) installed and copied **Migration (4.0.2)** into plugins folder like so `wp-content/plugins/matomo/plugins/Migration`

Than i activated **Migration** via `plugin:activate` and got the output `Activated plugin Migration` but calling `migration:measurable` returns error bellow

```
[InvalidArgumentException]                                   
There are no commands defined in the "migration" namespace.
```

Also done `cache:clear` like mentioned in #35 but plugin still on status **Not activated** and commands are not listed and same error.
