### ISSUE TITLE
Graphs/overviews incomplete after migration

### ISSUE THREAD

**Issue by koehnlein** [matomo-org/plugin-Migration#19]
Hi,

I currently was migrating a Site and realized, there is data missing in the graphs/overviews.

Here two screenshots from the old instance and the new instance. In the bottom left, you can see, there is data for the last 24 hours, but all the graphs and overviews show *0*. Do you have any idea how to solve this? Is this caused by the Migration plugin? Or do I need to execute any CLI task to generate/correct the graphs?

| data in old instance | data in new instance |
| --- | --- |
| ![Bildschirmfoto 2020-05-04 um 13 02 00](https://user-images.githubusercontent.com/16088567/80959744-b3c26c00-8e07-11ea-8acc-41cb68145d73.png) | ![Bildschirmfoto 2020-05-04 um 13 01 47](https://user-images.githubusercontent.com/16088567/80959752-bae97a00-8e07-11ea-9566-4b9bd895c840.png) |

**Comment by tsteur** [comment]
Did you migrate the instance a few days ago maybe and aren't tracking the data into the new instance?

**Comment by koehnlein** [comment]
Looks like, it was not the Plugin's fault. The graph is generated now, but unfortunately not all days. But I guess, that's another problem and not related with the plugin. :-(

![Bildschirmfoto 2020-05-05 um 15 31 04](https://user-images.githubusercontent.com/16088567/81071932-b1364400-8ee5-11ea-94e7-2d2671b965ba.png)

**Comment by tsteur** [comment]
Thanks for letting us know @koehnlein I'll close the issue for now. Seems one day wasn't generated? Maybe try to invalidate the data for that particular day if you can see https://matomo.org/faq/how-to/faq_155/ and maybe the data will become available
