### ISSUE TITLE
Error when installing plugin: Inexistent Matomo version required

### ISSUE THREAD

**Issue by TRILOS** [matomo-org/plugin-Migration#22]
After trying plugin-Migration v3.0.5 ZIP upload to Matomo 3.13.1 (DE), an error occured:
"Error in Matomo: Bitte aktualisieren Sie Matomo 3.13.1 auf eine neuere Version, Matomo &gt;=4.0.0-b1,&lt;5.0.0-b1 wird ben\xc3\xb6tigt., "
("Please update to a newer version, Matomo >=4.0.0-b1,<5.0.0-b1 is required")
But there´s no Matomo version >=4!

**Comment by tsteur** [comment]
You've probably downloaded the plugin from Github for our 4.x which is in development but not released yet. You want to download it from https://plugins.matomo.org/Migration

**Comment by TRILOS** [comment]
Thank you @tsteur for clearing this up quickly. Let me note what led to this misunderstanding and should be improved:
- I´ve expected the compatibility because Source etc. on https://plugins.matomo.org/Migration linked to https://github.com/matomo-org/plugin-Migration
- It seems there´s  no information, even no system requirement notice for v3.0.5 or mention of these two different versions in the content on https://github.com/matomo-org/plugin-Migration or when running the script

**Comment by tsteur** [comment]
@TRILOS  the source code for 3.x is in https://github.com/matomo-org/plugin-Migration/tree/3.x-dev

Generally we don't recommend using code from github. They may include files which you won't want to deploy on production. I'd definitely recommend using our plugins from the marketplace.
