### ISSUE TITLE
Manual plugin installation failed in cause of invalid plugin name

### ISSUE THREAD

**Issue by TRILOS** [matomo-org/plugin-Migration#23]
Copy v3.0.5 files to new folder /plugin-Migration-4.x-dev in /plugins leads to error
"The plugin name 'plugin-Migration-4.x-dev' is not a valid plugin name"

**Comment by TRILOS** [comment]
Renaming folder to /Migration helps (*facepalm*)

**Comment by tsteur** [comment]
You'll want to download the plugin from https://plugins.matomo.org/Migration for your Matomo version (currently only available for 3.x)
