### ISSUE TITLE
wp migration [Zend_Db_Adapter_Mysqli_Exception]   Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by SeriForte** [matomo-org/plugin-Migration#32]
I'm not sure what I miss, or if It is a bug, when I try to migrate the data from the wordpress matomo plugin "Matomo Analytics" to a new "On-Promise" installation. 

1. install the matomo marketplace plugin on the wordpress installation
2. install the matomo migration plugin form the matomo marketplace (btw. where can I see the Version?)
3. login to webserver via ssh to wp installation directory (where you can see wp-content etc.)
4. run `php wp-content/plugins/matomo/app/console migration:measurable --dry-run --source-idsite=1 --target-db-prefix=wp_matomo_ --target-db-host=NEW_DB_HOST --target-db-username=NEW_DB_USER --target-db-password=NEW_DB_PWD --target-db-name=NEW_DB_NAME`  (with or without prefix, same result)

Unfortunately I got a following error `[Zend_Db_Adapter_Mysqli_Exception]   Access denied for user ''@'localhost' (using password: NO)`

The `NEW_DB_USER` is set to a valid name, which is not `''@'localhost'` or similar
The `NEW_DB_HOST` is set to the host, which I see in phpMyAdmin for User: NEW_DB_USER@**NEW_DB_HOST**
The `NEW_DB_PWD` is set to the the matching pwd for NEW_DB_USER

If I miss something, could you update or describe the migration process in more detail?

Thank you very much.

**Comment by tsteur** [comment]
Hi @SeriForte I was able to reproduce this and fixed it. The patch will be only included in the release for Matomo for WordPress 4 (which is due in one week).

You could already now apply this patch see https://github.com/matomo-org/plugin-Migration/pull/33/files#diff-ba49c23268e9c1cc76cde82fe0534994bdeb215b8d3d22f4765f91dbe3ba16b3R233-R237 to `wp-content/plugins/Migration/TargetDb.php` in case you are familiar with patching files on a WP server. This should work assuming both DBs have the same DB schema.
