### ISSUE TITLE
Migration InvalidArgumentException

### ISSUE THREAD

**Issue by netthinks** [matomo-org/plugin-Migration#35]
Using Matomo 4.2.1 on both sides.
After calling
`./console migration:measurable --source-idsite=19 --target-db-host=xxx --target-db-username=xxx --target-db-password=xxx --target-db-name=xxx --target-db-prefix=matomo_`

it throws
```
  [InvalidArgumentException]
  There are no commands defined in the "migration" namespace.
```
  
  Plugin is activated. What could be the problem?

**Comment by tsteur** [comment]
@netthinks it indicates usually that the plugin is not activated. I know you mention it is activated but might be worth running those commands just to be sure:

```
./console plugin:activate Migration
./console cache:clear
```

And then try it again. Does this help maybe @netthinks ?

**Comment by netthinks** [comment]
strange: after calling  ./console plugin:activate Migration, an exception was thrown:
```
[Exception]
  Plugin 'Migration' cannot be found in the filesystem in plugins/ directory.
```
I've installed the plugin manually (upload in folder plugins/) and tried to activate it again:
Migration requires Matomo >=4.0.0-b1.

Pluginlist shows it is activated, but if I call the migration, the same error occurs:
```
  [InvalidArgumentException]
  There are no commands defined in the "migration" namespace.
```
Strange: if I install the plugin from marketplace, there is no folder "Migfration" in plugins folder... But it is listed in plugin page and marked as activated?!?

**Comment by netthinks** [comment]
looks better now, db tables must be updated, so I think it should work. Thanks!
