### ISSUE TITLE
Syntax error for option table when migrating

### ISSUE THREAD

**Issue by Starker3** [matomo-org/plugin-Migration#52]
When performing a migration the following error occurs:
```
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'option (`option_name`,`option_value`,`autoload`) VALUES('2_annotations','a:1:{i:' at l
```

This error doesn't show up when performing a dry run and was encountered when migrating between two identical instances on Cloud

This is the command used to start the migration:
```
sudo -u apache -E bash -c "time php -d memory_limit=11G /var/www/html/console migration:measurable  --source-idsite=3 --target-db-host=${host} --target-db-username=${username} --target-db-name=${dbname} --target-db-password=${password} --matomo-domain=SUBDOMAIN.matomo.cloud"
```

**Comment by snake14** [comment]
Hi @Starker3 . I'm thinking that the issue might be that the option table isn't prefixed and `option` isn't surrounded by ticks (`). What do  you think @AltamashShaikh ?

**Comment by Starker3** [comment]
@snake14 Indeed, we managed to fix it using a simple patch:
```
diff --git a/TargetDb.php b/TargetDb.php
index 4cb4792..7128e40 100644
--- a/TargetDb.php
+++ b/TargetDb.php
@@ -188,7 +188,7 @@ class TargetDb
 
         $tablePrefixed = $this->prefixTable($table);
 
-        $sql = sprintf('INSERT INTO %s (`%s`) VALUES(%s)', $tablePrefixed, $columns, $fields);
+        $sql = sprintf('INSERT INTO `%s` (`%s`) VALUES(%s)', $tablePrefixed, $columns, $fields);
         $bind = array_values($row);
 
         if ($this->dryRun) {
```

I was able to complete the migration after changing the above. I guess in this case it might just be an issue for databases that don't use a prefix (Which we don't use on Cloud). It's strange though since this isn't the first migration I've done on Cloud but it was the first time I encountered this error.

**Comment by snake14** [comment]
Ah, yep. Looks like it's as I suspected. It's strange that this hasn't cropped up until now. Maybe most clients don't use annotations?

**Comment by AltamashShaikh** [comment]
> Hi @Starker3 . I'm thinking that the issue might be that the option table isn't prefixed and `option` isn't surrounded by ticks (`). What do you think @AltamashShaikh ?

Yes we recently face the similar issue in of our plugins update script where there was no prefix

**Comment by snake14** [comment]
@Starker3 I just merged the fix and it should be included in the next release of this plugin.
