### ISSUE TITLE
PHP Fatal error:  Declaration of Symfony\Bridge\Monolog\Handler\ConsoleHandler::handle(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::handle(array $record)

### ISSUE THREAD

**Issue by wbdb** [matomo-org/plugin-Migration#55]
### Migration-4.0.3

Command:
`/opt/plesk/php/8.1/bin/php wp-content/plugins/matomo/app/console migration:measurable --source-idsite=1 --target-db-host='127.0.0.1' --target-db-username='user1' --target-db-password='password!' --target-db-name='matomo_example'`

**Tested with PHP 7.4 and 8.1**

`PHP Fatal error:  Declaration of Symfony\Bridge\Monolog\Handler\ConsoleHandler::handle(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::handle(array $record): bool in /var/www/vhosts/example.com/wp-content/plugins/matomo/app/vendor/symfony/monolog-bridge/Symfony/Bridge/Monolog/Handler/ConsoleHandler.php on line 88`

**Comment by snake14** [comment]
Hi @wbdb . I'm sorry that you are experiencing this issue. It looks like the Monolog version used by our plugin is conflicting with the version used by another plugin. Sadly, this is a known issue. A permanent fix is supposed to be part of the Matomo 5 release. In the meantime, you can check the [list of WordPress plugins that are known to have compatibility issues](https://matomo.org/faq/wordpress/which-plugins-is-matomo-for-wordpress-known-to-be-not-compatible-with/) and try disabling them.
