### ISSUE TITLE
migration gives  warning Undefined array key 9434022

### ISSUE THREAD

**Issue by michelwigbers** [matomo-org/plugin-Migration#61]
Hello, 

I got the following warning during the migration.
WARNING [2023-11-28 10:49:56] 56  /var/www/html/plugins/Migration/Migrations/LogMigration.php(98): Warning - Undefined array key 9434022 - Matomo 4.14.2 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

Only dif between the two is a difference that there was one plugin extra installed in the old matomo. It was the HeatMapSessionRecording plugin. 

After completion I don't see the site in the new matomo instance. 

Kind Regards,

**Comment by snake14** [comment]
Hi @michelwigbers . Thank you for taking the time to create this issue. That warning shouldn't prevent the migration from completing. Have you tried using the `--verbose` or `-vvv` option to get more output during the migration? Are there any errors in your application or Apache logs?

**Comment by michelwigbers** [comment]
Also with the --vvv option. It does not give any pointers. Logs of apache are clean. What is the application?

**Comment by snake14** [comment]
Hi @michelwigbers . By the application, I was referring to the instance of Matomo on which you were running the console command. My local instance of Matomo logs errors to `tmp/logs/matomo.log` in the root of the installed directory. Although, if nothing was displayed while using the verbose option, there's likely nothing in the application log.

Just to confirm, you're running the console command on the source Matomo server (old Matomo instance) and providing the database credentials of the destination server (new Matomo instance)? What command are you running? For example, when I test the plugin on my local Matomo install, I run the following:
```
./console migration:measurable --source-idsite=50 --target-db-host=127.0.01 --target-db-username=matomo --target-db-name="matomo_dev_db" --target-db-password='{myDevDbPassowrd}' --target-db-prefix=matomo_ --skip-logs --skip-archives -vvv
```

**Comment by michelwigbers** [comment]
```
time docker exec -it matomo /var/www/html/console migration:measurable --source-idsite=2 --target-db-host=xx.xxx.xxx.xxx --target-db-port=3328 --target-db-username=matomo --target-db-password=xxx --target-db-name=matomo --target-db-prefix=matomo_ --verbose
``` 

As it is in docker I run: 

```
 docker logs -f matomo
```

**Comment by snake14** [comment]
Hmm. I haven't used the Matomo docker image, but that looks like it should work. Any recommendations @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@michelwigbers Can you replace this [line](https://github.com/matomo-org/plugin-Migration/blob/4.x-dev/Migrations/LogMigration.php#L97) with below line and check again ?

```
if (isset($row['idlink_va']) && !empty($visitorLinkActionMap[$row['idlink_va']])) {
```

I doubt it will have much effect and for logging can you check this [FAQ](https://matomo.org/faq/how-to/faq_20991/) and make relevant changes and see if it makes a log file with any info under `/your/path/to/matomo/tmp/logs/matomo.log`

**Comment by michelwigbers** [comment]
Import worked now with the option: --skip-logs. Thus the problem was/is there. I will close. Thank you for your help.

**Comment by michelwigbers** [comment]
thank you

**Comment by snake14** [comment]
Hi @michelwigbers . I'm glad that you got things working.

**Comment by michelwigbers** [comment]
without the log visits it goes fine. Tried today with the visits.. still nothing :-(. 

this is the output in the console
Processing SiteMigration at 2023-12-05 07:57:57
Target site is 23 at 2023-12-05 07:57:57
Processed SiteMigration at 2023-12-05 07:57:57
Processing SiteUrlMigration at 2023-12-05 07:57:57
Found 0 site urls at 2023-12-05 07:57:57
Processed SiteUrlMigration at 2023-12-05 07:57:57
Processing SiteSettingMigration at 2023-12-05 07:57:57
Found 0 site settings at 2023-12-05 07:57:57
Processed SiteSettingMigration at 2023-12-05 07:57:57
Processing GoalsMigration at 2023-12-05 07:57:57
Found 2 goals at 2023-12-05 07:57:57
Processed GoalsMigration at 2023-12-05 07:57:57
Processing SegmentsMigration at 2023-12-05 07:57:57
Found 12 segments at 2023-12-05 07:57:57
Processed SegmentsMigration at 2023-12-05 07:57:57
Processing AnnotationsMigration at 2023-12-05 07:57:57
Processed AnnotationsMigration at 2023-12-05 07:57:57
Processing CustomDimensionMigration at 2023-12-05 07:57:57
Found 0 custom dimensions at 2023-12-05 07:57:58
Processed CustomDimensionMigration at 2023-12-05 07:57:58
Processing LogMigration at 2023-12-05 07:57:58
Found 1243990 visits at 2023-12-05 07:57:58
Migrated 5% of visits at 2023-12-05 08:05:55
Migrated 10% of visits at 2023-12-05 08:14:00
Migrated 20% of visits at 2023-12-05 08:29:58
Migrated 40% of visits at 2023-12-05 09:03:41
Migrated 60% of visits at 2023-12-05 10:06:19
Migrated 80% of visits at 2023-12-05 11:42:14
Migrated 90% of visits at 2023-12-05 12:27:08
Migrated 1243990 visits. The number of migrated visits may be higher if data is still tracked into the source Matomo while migrating the data at 2023-12-05 13:15:58
Processed LogMigration at 2023-12-05 13:15:58
Processing ArchiveMigration at 2023-12-05 13:15:58
Found 153 archive tables at 2023-12-05 13:15:59
Starting to migrate archive table matomo_archive_blob_2013_01 at 2023-12-05 13:15:59
Migrated archive table archive_blob_2013_01 at 2023-12-05 13:15:59
Starting to migrate archive table matomo_archive_blob_2014_01 at 2023-12-05 13:15:59
Migrated archive table archive_blob_2014_01 at 2023-12-05 13:15:59
Starting to migrate archive table matomo_archive_blob_2015_01 at 2023-12-05 13:15:59
Migrated archive table archive_blob_2015_01 at 2023-12-05 13:15:59
Starting to migrate archive table matomo_archive_blob_2016_01 at 2023-12-05 13:15:59
Migrated archive table archive_blob_2016_01 at 2023-12-05 13:15:59
Starting to migrate archive table matomo_archive_blob_2017_01 at 2023-12-05 13:15:59
Migrated archive table archive_blob_2017_01 at 2023-12-05 13:15:59
Starting to migrate archive table matomo_archive_blob_2018_01 at 2023-12-05 13:15:59
Migrated archive table archive_blob_2018_01 at 2023-12-05 13:16:12
Starting to migrate archive table matomo_archive_blob_2018_02 at 2023-12-05 13:16:12
Migrated archive table archive_blob_2018_02 at 2023-12-05 13:16:12
Starting to migrate archive table matomo_archive_blob_2018_03 at 2023-12-05 13:16:12
Migrated archive table archive_blob_2018_03 at 2023-12-05 13:16:12
Starting to migrate archive table matomo_archive_blob_2018_04 at 2023-12-05 13:16:12
Migrated archive table archive_blob_2018_04 at 2023-12-05 13:16:12
Starting to migrate archive table matomo_archive_blob_2018_05 at 2023-12-05 13:16:12
Migrated archive table archive_blob_2018_05 at 2023-12-05 13:16:13
Starting to migrate archive table matomo_archive_blob_2018_06 at 2023-12-05 13:16:13
Migrated archive table archive_blob_2018_06 at 2023-12-05 13:16:25
Starting to migrate archive table matomo_archive_blob_2018_07 at 2023-12-05 13:16:25
Migrated archive table archive_blob_2018_07 at 2023-12-05 13:16:31
Starting to migrate archive table matomo_archive_blob_2018_08 at 2023-12-05 13:16:31
Migrated archive table archive_blob_2018_08 at 2023-12-05 13:16:33
Starting to migrate archive table matomo_archive_blob_2018_09 at 2023-12-05 13:16:33
Migrated archive table archive_blob_2018_09 at 2023-12-05 13:16:35
Starting to migrate archive table matomo_archive_blob_2018_10 at 2023-12-05 13:16:35
Migrated archive table archive_blob_2018_10 at 2023-12-05 13:16:37
Starting to migrate archive table matomo_archive_blob_2018_11 at 2023-12-05 13:16:37
Migrated archive table archive_blob_2018_11 at 2023-12-05 13:16:37
Starting to migrate archive table matomo_archive_blob_2018_12 at 2023-12-05 13:16:37
Migrated archive table archive_blob_2018_12 at 2023-12-05 13:16:38
Starting to migrate archive table matomo_archive_blob_2019_01 at 2023-12-05 13:16:38
Migrated archive table archive_blob_2019_01 at 2023-12-05 13:16:49
Starting to migrate archive table matomo_archive_blob_2019_02 at 2023-12-05 13:16:49
Migrated archive table archive_blob_2019_02 at 2023-12-05 13:16:50
Starting to migrate archive table matomo_archive_blob_2019_03 at 2023-12-05 13:16:50
Migrated archive table archive_blob_2019_03 at 2023-12-05 13:16:50
Starting to migrate archive table matomo_archive_blob_2019_04 at 2023-12-05 13:16:50
Migrated archive table archive_blob_2019_04 at 2023-12-05 13:16:51
Starting to migrate archive table matomo_archive_blob_2019_05 at 2023-12-05 13:16:51
Migrated archive table archive_blob_2019_05 at 2023-12-05 13:16:57
Starting to migrate archive table matomo_archive_blob_2019_06 at 2023-12-05 13:16:57
Migrated archive table archive_blob_2019_06 at 2023-12-05 13:16:58
Starting to migrate archive table matomo_archive_blob_2019_07 at 2023-12-05 13:16:58
Migrated archive table archive_blob_2019_07 at 2023-12-05 13:16:59
Starting to migrate archive table matomo_archive_blob_2019_08 at 2023-12-05 13:16:59
Migrated archive table archive_blob_2019_08 at 2023-12-05 13:17:01
Starting to migrate archive table matomo_archive_blob_2019_09 at 2023-12-05 13:17:01
Migrated archive table archive_blob_2019_09 at 2023-12-05 13:17:04
Starting to migrate archive table matomo_archive_blob_2019_10 at 2023-12-05 13:17:04
Migrated archive table archive_blob_2019_10 at 2023-12-05 13:17:08
Starting to migrate archive table matomo_archive_blob_2019_11 at 2023-12-05 13:17:08
Migrated archive table archive_blob_2019_11 at 2023-12-05 13:17:08
Starting to migrate archive table matomo_archive_blob_2019_12 at 2023-12-05 13:17:08
Migrated archive table archive_blob_2019_12 at 2023-12-05 13:17:09
Starting to migrate archive table matomo_archive_blob_2020_01 at 2023-12-05 13:17:09
Migrated archive table archive_blob_2020_01 at 2023-12-05 13:22:02
Starting to migrate archive table matomo_archive_blob_2020_02 at 2023-12-05 13:22:02
Migrated archive table archive_blob_2020_02 at 2023-12-05 13:22:05
Starting to migrate archive table matomo_archive_blob_2020_03 at 2023-12-05 13:22:05
Migrated archive table archive_blob_2020_03 at 2023-12-05 13:22:06
Starting to migrate archive table matomo_archive_blob_2020_04 at 2023-12-05 13:22:06
Migrated archive table archive_blob_2020_04 at 2023-12-05 13:22:13
Starting to migrate archive table matomo_archive_blob_2020_05 at 2023-12-05 13:22:13
Migrated archive table archive_blob_2020_05 at 2023-12-05 13:22:16
Starting to migrate archive table matomo_archive_blob_2020_06 at 2023-12-05 13:22:16
Migrated archive table archive_blob_2020_06 at 2023-12-05 13:22:20
Starting to migrate archive table matomo_archive_blob_2020_07 at 2023-12-05 13:22:20
Migrated archive table archive_blob_2020_07 at 2023-12-05 13:22:27
Starting to migrate archive table matomo_archive_blob_2020_08 at 2023-12-05 13:22:27
Migrated archive table archive_blob_2020_08 at 2023-12-05 13:22:27
Starting to migrate archive table matomo_archive_blob_2020_09 at 2023-12-05 13:22:27
Migrated archive table archive_blob_2020_09 at 2023-12-05 13:22:28
Starting to migrate archive table matomo_archive_blob_2020_10 at 2023-12-05 13:22:28
Migrated archive table archive_blob_2020_10 at 2023-12-05 13:22:31
Starting to migrate archive table matomo_archive_blob_2020_11 at 2023-12-05 13:22:31
Migrated archive table archive_blob_2020_11 at 2023-12-05 13:22:31
Starting to migrate archive table matomo_archive_blob_2020_12 at 2023-12-05 13:22:31
Migrated archive table archive_blob_2020_12 at 2023-12-05 13:23:41
Starting to migrate archive table matomo_archive_blob_2021_01 at 2023-12-05 13:23:41
Migrated archive table archive_blob_2021_01 at 2023-12-05 13:24:04
Starting to migrate archive table matomo_archive_blob_2021_02 at 2023-12-05 13:24:04
Migrated archive table archive_blob_2021_02 at 2023-12-05 13:24:15
Starting to migrate archive table matomo_archive_blob_2021_03 at 2023-12-05 13:24:15
Migrated archive table archive_blob_2021_03 at 2023-12-05 13:24:17
Starting to migrate archive table matomo_archive_blob_2021_04 at 2023-12-05 13:24:17
Migrated archive table archive_blob_2021_04 at 2023-12-05 13:24:37
Starting to migrate archive table matomo_archive_blob_2021_05 at 2023-12-05 13:24:37
Migrated archive table archive_blob_2021_05 at 2023-12-05 13:24:48
Starting to migrate archive table matomo_archive_blob_2021_06 at 2023-12-05 13:24:48
Migrated archive table archive_blob_2021_06 at 2023-12-05 13:25:25
Starting to migrate archive table matomo_archive_blob_2021_07 at 2023-12-05 13:25:25
Migrated archive table archive_blob_2021_07 at 2023-12-05 13:25:39
Starting to migrate archive table matomo_archive_blob_2021_08 at 2023-12-05 13:25:39
Migrated archive table archive_blob_2021_08 at 2023-12-05 13:25:43
Starting to migrate archive table matomo_archive_blob_2021_09 at 2023-12-05 13:25:43
Migrated archive table archive_blob_2021_09 at 2023-12-05 13:25:52
Starting to migrate archive table matomo_archive_blob_2021_10 at 2023-12-05 13:25:52
Migrated archive table archive_blob_2021_10 at 2023-12-05 13:25:54
Starting to migrate archive table matomo_archive_blob_2021_11 at 2023-12-05 13:25:54
Migrated archive table archive_blob_2021_11 at 2023-12-05 13:26:47
Starting to migrate archive table matomo_archive_blob_2021_12 at 2023-12-05 13:26:47
Migrated archive table archive_blob_2021_12 at 2023-12-05 13:28:01
Starting to migrate archive table matomo_archive_blob_2022_01 at 2023-12-05 13:28:01
Migrated archive table archive_blob_2022_01 at 2023-12-05 13:28:53
Starting to migrate archive table matomo_archive_blob_2022_02 at 2023-12-05 13:28:53

real    357m13.522s
user    0m1.008s
sys     0m10.024s

The logging does not show anything. So I am a bit lost in this.

**Comment by snake14** [comment]
Hi @michelwigbers . I'm sorry to hear that you're still having trouble. It looks like it might have stopped before completing the migration of the archives. I wonder if something failed in there and caused the whole transaction to roll back. Have you tried using the `--skip-archives` option? If it's indeed a transaction issue, you could try using the `--disable-db-transactions` option as well, but I would lean toward not migrating the archives and simply running the `core:archive` command on the new Matomo instance to build all the archives.

**Comment by michelwigbers** [comment]
Finally with the skip-archives option it works!

**Comment by snake14** [comment]
@michelwigbers I'm happy to hear that it worked for you. Sorry for not recommending that option sooner.
